# Generated by Django 4.2.8 on 2024-01-12 08:09

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "movieCd",
                    models.CharField(
                        db_column="movieCD",
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("movieNm", models.CharField(db_column="title_ko", max_length=100)),
                (
                    "movieNmEn",
                    models.CharField(db_column="title_original", max_length=100),
                ),
                (
                    "nationAlt",
                    models.CharField(db_column="prod_country", max_length=50),
                ),
                ("openDt", models.DateField(db_column="release_date")),
            ],
        ),
    ]
