# Generated by Django 4.2.8 on 2024-01-15 17:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contentTest", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="movie",
            name="movieNmEn",
        ),
        migrations.AddField(
            model_name="movie",
            name="movieNmOg",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="movie",
            name="plot",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="movie",
            name="poster",
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name="movie",
            name="showTm",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="movie",
            name="movieCd",
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="movie",
            name="movieNm",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="movie",
            name="nationAlt",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="movie",
            name="openDt",
            field=models.DateField(db_column="release_date", null=True),
        ),
    ]
