# Generated by Django 4.2.8 on 2024-01-16 19:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "contentTest",
            "0002_remove_movie_movienmen_movie_movienmog_movie_plot_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="movieNmOg",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="movie",
            name="openDt",
            field=models.CharField(max_length=10, null=True),
        ),
    ]
