# Generated by Django 4.2.8 on 2024-01-24 13:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("contentTest", "0003_alter_movie_movienmog_alter_movie_opendt"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Movie",
            new_name="TransmitMovie",
        ),
    ]
