# Generated by Django 4.2.8 on 2024-01-16 12:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("waffleAuth", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="waffleuser",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
