# Generated by Django 4.2.8 on 2024-01-30 13:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("waffleAuth", "0004_alter_waffleuser_background_photo_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="waffleuser",
            name="bio",
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
