# Generated by Django 4.2.8 on 2024-01-12 08:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "movieCD",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("title_ko", models.CharField(max_length=100)),
                ("title_original", models.CharField(max_length=100)),
                ("plot", models.TextField()),
                ("runtime", models.IntegerField()),
                ("prod_country", models.CharField(max_length=50)),
                ("poster", models.URLField()),
                ("release_date", models.DateField()),
                ("cumulative_audience", models.IntegerField()),
                ("screening", models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name="People",
            fields=[
                (
                    "peopleCD",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=50)),
                ("is_actor", models.BooleanField()),
                ("is_director", models.BooleanField()),
                ("is_writer", models.BooleanField()),
                (
                    "directed_movies",
                    models.ManyToManyField(
                        blank=True, related_name="directors", to="content.movie"
                    ),
                ),
                (
                    "starred_movies",
                    models.ManyToManyField(
                        blank=True, related_name="casts", to="content.movie"
                    ),
                ),
                (
                    "written_movies",
                    models.ManyToManyField(
                        blank=True, related_name="writers", to="content.movie"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="State",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user_state",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("want_to_watch", "want_to_watch"),
                            ("watching", "watching"),
                            ("not_interested", "not_interested"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "movie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="content.movie"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("role", models.CharField(max_length=50)),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="content.people"
                    ),
                ),
                (
                    "movie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="content.movie"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Rating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rate",
                    models.DecimalField(
                        choices=[
                            (0.5, "0.5"),
                            (1.0, "1.0"),
                            (1.5, "1.5"),
                            (2.0, "2.0"),
                            (2.5, "2.5"),
                            (3.0, "3.0"),
                            (3.5, "3.5"),
                            (4.0, "4.0"),
                            (4.5, "4.5"),
                            (5.0, "5.0"),
                        ],
                        decimal_places=1,
                        default=0.0,
                        max_digits=3,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "movie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="content.movie"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("genre", models.CharField(max_length=50)),
                (
                    "movies",
                    models.ManyToManyField(related_name="genres", to="content.movie"),
                ),
            ],
        ),
    ]
