# Generated by Django 4.2.8 on 2024-01-16 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="people",
            name="photo",
            field=models.FileField(blank=True, upload_to="people_photos/"),
        ),
        migrations.AlterField(
            model_name="role",
            name="actor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="actor_roles",
                to="content.people",
            ),
        ),
        migrations.AlterField(
            model_name="role",
            name="movie",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="castings",
                to="content.movie",
            ),
        ),
    ]
