# Generated by Django 4.2.8 on 2024-01-17 08:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0002_people_photo_alter_role_actor_alter_role_movie"),
    ]

    operations = [
        migrations.AddField(
            model_name="role",
            name="priority",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="genre",
            name="movies",
            field=models.ManyToManyField(
                blank=True, related_name="genres", to="content.movie"
            ),
        ),
        migrations.AlterField(
            model_name="movie",
            name="cumulative_audience",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="movie",
            name="screening",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="people",
            name="is_actor",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="people",
            name="is_director",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="people",
            name="is_writer",
            field=models.BooleanField(default=False),
        ),
    ]
