# Generated by Django 4.2.8 on 2024-01-17 10:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0003_role_priority_alter_genre_movies_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="role",
            options={"ordering": ("priority",)},
        ),
    ]
