# Generated by Django 4.2.8 on 2024-01-23 08:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0005_carousel"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="rating",
            constraint=models.UniqueConstraint(
                fields=("created_by", "movie"), name="unique rating"
            ),
        ),
    ]
