# Generated by Django 4.2.8 on 2024-01-24 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0006_rating_unique_rating"),
    ]

    operations = [
        migrations.CreateModel(
            name="BoxOffice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "db_table": "new_box_office",
            },
        ),
        migrations.CreateModel(
            name="BoxOfficeMovie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rank", models.IntegerField()),
                (
                    "box_office",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="content.boxoffice",
                    ),
                ),
                (
                    "movie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="content.movie"
                    ),
                ),
            ],
            options={
                "db_table": "new_box_office_movie",
            },
        ),
        migrations.AddField(
            model_name="boxoffice",
            name="movies",
            field=models.ManyToManyField(
                through="content.BoxOfficeMovie", to="content.movie"
            ),
        ),
        migrations.AddConstraint(
            model_name="boxofficemovie",
            constraint=models.CheckConstraint(
                check=models.Q(("rank__gte", 1)), name="boxoffice_rank_gte_1"
            ),
        ),
        migrations.AddConstraint(
            model_name="boxofficemovie",
            constraint=models.CheckConstraint(
                check=models.Q(("rank__lte", 10)), name="boxoffice_rank_lte_10"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="boxofficemovie",
            unique_together={("box_office", "rank"), ("box_office", "movie")},
        ),
    ]
