# Generated by Django 4.2.8 on 2024-01-24 13:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0007_boxoffice_boxofficemovie_boxoffice_movies_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="boxoffice",
            name="date",
            field=models.DateField(null=True),
        ),
    ]
