# Generated by Django 4.2.8 on 2024-01-23 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("comment", "0002_comment_has_spoiler"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reply",
            name="comment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="replies",
                to="comment.comment",
            ),
        ),
        migrations.AddConstraint(
            model_name="comment",
            constraint=models.UniqueConstraint(
                fields=("created_by", "movie"), name="unique comment"
            ),
        ),
    ]
